services:
  nginx:
    build: nginx/
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../frontend/public:/var/www/html
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16